"""create topic

Revision ID: 854cfc45412c
Revises: 5a5a4b4a82ba
Create Date: 2026-09-04 21:43:04.580221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854cfc45412c'
down_revision: Union[str, Sequence[str], None] = '5a5a4b4a82ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'name', name='uq_topic_subject_id_name')
    )
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=False)
    op.create_index(op.f('ix_topic_subject_id'), 'topic', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_subject_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
