"""add correct_answer to question

Revision ID: b74ff08269d0
Revises: 854cfc45412c
Create Date: 2026-09-05 02:07:42.960034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74ff08269d0'
down_revision: Union[str, Sequence[str], None] = '854cfc45412c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('correct_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'correct_answer')
    # ### end Alembic commands ###
